ORG 0000H
SETB P0.1;MAKING P0.1 AS INPUT
SETB P0.3;MAKING P0.3 AS OFF
CLR C;CLEARING CARRY
LOOP:MOV C,P0.1;COPYING P0.1 TO CARRY
CPL C;COMPLEMENTING CARRY
MOV P0.3,C;COPYING CARRY TO P0.3
SJMP LOOP;JUMPING TO LOOP
